use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :cotoami, Cotoami.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "cotoa.me", port: 443],
  cache_static_manifest: "priv/static/manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configure your database
config :cotoami, Cotoami.Repo,
  adapter: Ecto.Adapters.Postgres,
  loggers: [Cotoami.Repo.Instrumenter],
  username: System.get_env("COTOAMI_REPO_USER"),
  password: System.get_env("COTOAMI_REPO_PASSWORD"),
  database: System.get_env("COTOAMI_REPO_DATABASE"),
  hostname: System.get_env("COTOAMI_REPO_HOST"),
  pool_size: 5
